### En este script, buscaré hacer crossmatch del dataframe que contiene features de los stamps
con otro dataframe que contiene las columnas de los flujos para aperturas de distinto radio (Obtenidos del tractor catalog)

- los radios de apertura que se consideran son hasta un radio de 3.5 [arcsec], esto es porque s eprobarán en el nivel con mejor resolución.
- solo se agregan los flujos de apertura considerando banda g y r.

![imagen de apertura de flujos](../../figures/aperture_fluxes.jpg)

In [1]:
## Importación de librerías

import numpy as np
import pandas as pd

In [ ]:
df1 = pd.read_csv("../../data/crossmatch_apflux.txt", sep=",")
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 29575 entries, 0 to 29574
Data columns (total 89 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ra_1                 29575 non-null  float64
 1   dec_1                29575 non-null  float64
 2   type_1               29575 non-null  str
 3   shape_r_1            29575 non-null  float64
 4   shape_e1_1           29575 non-null  float64
 5   shape_e2_1           29575 non-null  float64
 6   sersic_1             29575 non-null  float64
 7   ebv_1                29575 non-null  float64
 8   release              29575 non-null  int64
 9   brickid_1            29575 non-null  int64
 10  objid_1              29575 non-null  int64
 11  brick_primary        29575 non-null  bool
 12  brickname_1          29575 non-null  str
 13  maskbits_1           29575 non-null  int64
 14  fitbits_1            29575 non-null  int64
 15  flux_g_1             29575 non-null  float64
 16  flux_r_1             29575 non-null  float64
 17  flux_i_1             29575 non-null  float64
 18  flux_z_1             29575 non-null  float64
 19  flux_ivar_g_1        29575 non-null  float64
 20  flux_ivar_r_1        29575 non-null  float64
 21  flux_ivar_i_1        29575 non-null  float64
 22  flux_ivar_z_1        29575 non-null  float64
 23  mw_transmission_g_1  29575 non-null  float64
 24  mw_transmission_r_1  29575 non-null  float64
 25  mw_transmission_i_1  29575 non-null  float64
 26  mw_transmission_z_1  29575 non-null  float64
 27  apflux_g_0_5         29575 non-null  float64
 28  apflux_g_0_75        29575 non-null  float64
 29  apflux_g_1_0         29575 non-null  float64
 30  apflux_g_1_5         29575 non-null  float64
 31  apflux_g_2_0         29575 non-null  float64
 32  apflux_g_3_5         29575 non-null  float64
 33  apflux_r_0_5         29575 non-null  float64
 34  apflux_r_0_75        29575 non-null  float64
 35  apflux_r_1_0         29575 non-null  float64
 36  apflux_r_1_5         29575 non-null  float64
 37  apflux_r_2_0         29575 non-null  float64
 38  apflux_r_3_5         29575 non-null  float64
 39  id_1                 29575 non-null  str
 40  desi_id              29575 non-null  int64
 41  mean_fiber_ra        29575 non-null  float64
 42  mean_fiber_dec       29575 non-null  float64
 43  z                    29575 non-null  float64
 44  zerr                 29575 non-null  float64
 45  ra_2                 29575 non-null  float64
 46  dec_2                29575 non-null  float64
 47  type_2               29575 non-null  str
 48  shape_r_2            29575 non-null  float64
 49  shape_e1_2           29575 non-null  float64
 50  shape_e2_2           29575 non-null  float64
 51  sersic_2             29575 non-null  float64
 52  ebv_2                29575 non-null  float64
 53  brickid_2            29575 non-null  int64
 54  dchisq_psf           29575 non-null  float64
 55  dchisq_rex           29575 non-null  float64
 56  dchisq_exp           29575 non-null  float64
 57  dchisq_dev           29575 non-null  float64
 58  dchisq_ser           29575 non-null  float64
 59  id_2                 29575 non-null  str
 60  flux_g_2             29575 non-null  float64
 61  flux_r_2             29575 non-null  float64
 62  flux_i_2             29575 non-null  float64
 63  flux_z_2             29575 non-null  float64
 64  flux_w1              29575 non-null  float64
 65  flux_w2              29575 non-null  float64
 66  flux_w3              29575 non-null  float64
 67  flux_w4              29575 non-null  float64
 68  flux_ivar_g_2        29575 non-null  float64
 69  flux_ivar_r_2        29575 non-null  float64
 70  flux_ivar_i_2        29575 non-null  float64
 71  flux_ivar_z_2        29575 non-null  float64
 72  flux_ivar_w1         29575 non-null  float64
 73  flux_ivar_w2         29575 non-null  float64
 74  flux_ivar_w3         29575 non-null  float64
 75  flux_ivar_w4         29575 non-null  float64
 76  mw_transmission_i_2  29575 non-null  float64
 77  fitbits_2            29575 non-null  int64
 78  mw_transmission_w1   29575 non-null  float64
 79  brickname_2          29575 non-null  str
 80  mw_transmission_z_2  29575 non-null  float64
 81  mw_transmission_g_2  29575 non-null  float64
 82  maskbits_2           29575 non-null  int64
 83  mw_transmission_w2   29575 non-null  float64
 84  mw_transmission_w3   29575 non-null  float64
 85  objid_2              29575 non-null  int64
 86  mw_transmission_w4   29575 non-null  float64
 87  mw_transmission_r_2  29575 non-null  float64
 88  Separation           29575 non-null  float64
dtypes: bool(1), float64(72), int64(10), str(6)
memory usage: 23.0 MB

In [9]:
df1.columns.tolist()

['ra_1',
 'dec_1',
 'type_1',
 'shape_r_1',
 'shape_e1_1',
 'shape_e2_1',
 'sersic_1',
 'ebv_1',
 'release',
 'brickid_1',
 'objid_1',
 'brick_primary',
 'brickname_1',
 'maskbits_1',
 'fitbits_1',
 'flux_g_1',
 'flux_r_1',
 'flux_i_1',
 'flux_z_1',
 'flux_ivar_g_1',
 'flux_ivar_r_1',
 'flux_ivar_i_1',
 'flux_ivar_z_1',
 'mw_transmission_g_1',
 'mw_transmission_r_1',
 'mw_transmission_i_1',
 'mw_transmission_z_1',
 'apflux_g_0_5',
 'apflux_g_0_75',
 'apflux_g_1_0',
 'apflux_g_1_5',
 'apflux_g_2_0',
 'apflux_g_3_5',
 'apflux_r_0_5',
 'apflux_r_0_75',
 'apflux_r_1_0',
 'apflux_r_1_5',
 'apflux_r_2_0',
 'apflux_r_3_5',
 'id_1',
 'desi_id',
 'mean_fiber_ra',
 'mean_fiber_dec',
 'z',
 'zerr',
 'ra_2',
 'dec_2',
 'type_2',
 'shape_r_2',
 'shape_e1_2',
 'shape_e2_2',
 'sersic_2',
 'ebv_2',
 'brickid_2',
 'dchisq_psf',
 'dchisq_rex',
 'dchisq_exp',
 'dchisq_dev',
 'dchisq_ser',
 'id_2',
 'flux_g_2',
 'flux_r_2',
 'flux_i_2',
 'flux_z_2',
 'flux_w1',
 'flux_w2',
 'flux_w3',
 'flux_w4',
 'flux_ivar_g_2',
 'flux_ivar_r_2',
 'flux_ivar_i_2',
 'flux_ivar_z_2',
 'flux_ivar_w1',
 'flux_ivar_w2',
 'flux_ivar_w3',
 'flux_ivar_w4',
 'mw_transmission_i_2',
 'fitbits_2',
 'mw_transmission_w1',
 'brickname_2',
 'mw_transmission_z_2',
 'mw_transmission_g_2',
 'maskbits_2',
 'mw_transmission_w2',
 'mw_transmission_w3',
 'objid_2',
 'mw_transmission_w4',
 'mw_transmission_r_2',
 'Separation']

In [8]:
df2 = pd.read_csv("../../data/features_images_20260618.csv", sep=",")
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 29575 entries, 0 to 29574
Data columns (total 48 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   desi_id             29575 non-null  int64
 1   mean_fiber_ra       29575 non-null  float64
 2   mean_fiber_dec      29575 non-null  float64
 3   z                   29575 non-null  float64
 4   zerr                29575 non-null  float64
 5   ra                  29575 non-null  float64
 6   dec                 29575 non-null  float64
 7   type                29575 non-null  str
 8   shape_r             29575 non-null  float64
 9   shape_e1            29575 non-null  float64
 10  shape_e2            29575 non-null  float64
 11  sersic              29575 non-null  float64
 12  ebv                 29575 non-null  float64
 13  brickid             29575 non-null  int64
 14  dchisq_psf          29575 non-null  float64
 15  dchisq_rex          29575 non-null  float64
 16  dchisq_exp          29575 non-null  float64
 17  dchisq_dev          29575 non-null  float64
 18  dchisq_ser          29575 non-null  float64
 19  id                  29575 non-null  str
 20  flux_g              29575 non-null  float64
 21  flux_r              29575 non-null  float64
 22  flux_i              29575 non-null  float64
 23  flux_z              29575 non-null  float64
 24  flux_w1             29575 non-null  float64
 25  flux_w2             29575 non-null  float64
 26  flux_w3             29575 non-null  float64
 27  flux_w4             29575 non-null  float64
 28  flux_ivar_g         29575 non-null  float64
 29  flux_ivar_r         29575 non-null  float64
 30  flux_ivar_i         29575 non-null  float64
 31  flux_ivar_z         29575 non-null  float64
 32  flux_ivar_w1        29575 non-null  float64
 33  flux_ivar_w2        29575 non-null  float64
 34  flux_ivar_w3        29575 non-null  float64
 35  flux_ivar_w4        29575 non-null  float64
 36  mw_transmission_i   29575 non-null  float64
 37  fitbits             29575 non-null  int64
 38  mw_transmission_w1  29575 non-null  float64
 39  brickname           29575 non-null  str
 40  mw_transmission_z   29575 non-null  float64
 41  mw_transmission_g   29575 non-null  float64
 42  maskbits            29575 non-null  int64
 43  mw_transmission_w2  29575 non-null  float64
 44  mw_transmission_w3  29575 non-null  float64
 45  objid               29575 non-null  int64
 46  mw_transmission_w4  29575 non-null  float64
 47  mw_transmission_r   29575 non-null  float64
dtypes: float64(40), int64(5), str(3)
memory usage: 12.4 MB

In [12]:
df1.rename(columns={"id_1": "id"}, inplace=True)

In [13]:
cols = [
'apflux_g_0_5',
 'apflux_g_0_75',
 'apflux_g_1_0',
 'apflux_g_1_5',
 'apflux_g_2_0',
 'apflux_g_3_5',
 'apflux_r_0_5',
 'apflux_r_0_75',
 'apflux_r_1_0',
 'apflux_r_1_5',
 'apflux_r_2_0',
 'apflux_r_3_5',
]

df2 = df2.merge(df1[["id"] + cols], on="id", how="left")

In [14]:
df2

,desi_id,mean_fiber_ra,mean_fiber_dec,z,zerr,ra,dec,type,shape_r,shape_e1,...,apflux_g_1_0,apflux_g_1_5,apflux_g_2_0,apflux_g_3_5,apflux_r_0_5,apflux_r_0_75,apflux_r_1_0,apflux_r_1_5,apflux_r_2_0,apflux_r_3_5
0,39627636401508885,147.028920,-6.291707,0.863852,0.000078,147.028933,-6.291716,REX,1.202857,0.000000,...,0.306679,0.555034,0.785307,1.243743,0.258404,0.488116,0.749305,1.306617,1.734067,2.514392
1,39627654457984508,147.941447,-5.506874,1.160004,0.000053,147.941456,-5.506887,EXP,0.358474,-0.312599,...,0.202898,0.354575,0.539918,0.776514,0.123683,0.264468,0.435538,1.037667,1.891394,3.127400
2,39627720786707922,148.820687,-2.767029,0.333578,0.000005,148.820681,-2.767036,REX,0.305442,0.000000,...,0.432196,0.459907,0.494985,0.587780,0.237059,0.416074,0.544305,0.715038,0.916342,1.000228
3,39627660615225397,156.331311,-5.158549,0.159566,0.000016,156.331327,-5.158570,SER,0.509001,-0.049165,...,4.878023,6.728512,7.824271,9.243667,4.382093,7.794225,10.717669,14.697038,17.091011,20.054650
4,39627678684283452,156.207028,-4.541228,0.864645,0.000132,156.207011,-4.541233,REX,0.279362,0.000000,...,0.058437,0.098808,0.158887,0.277587,0.155351,0.270452,0.352012,0.480271,0.528621,0.778429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29570,39627968078679914,151.770335,7.574563,0.125753,0.000014,151.770339,7.574556,EXP,0.748664,0.079242,...,0.332436,0.542406,0.678002,0.896668,0.229990,0.446871,0.608541,0.856583,0.864000,0.983388
29571,39627805423568301,153.560091,0.738629,0.981242,0.000049,153.560079,0.738607,REX,0.830543,0.000000,...,0.324660,0.518564,0.659066,0.841027,0.140413,0.271792,0.420471,0.671638,0.848212,1.060489
29572,39627841737851674,158.033419,2.225420,0.905659,0.000019,158.033423,2.225414,REX,0.405263,0.000000,...,0.455027,0.623155,0.682241,0.802813,0.244901,0.417597,0.585954,0.830851,0.966104,1.198929
29573,39627889993320651,156.590201,4.210283,0.073323,0.000003,156.590189,4.210277,SER,1.827961,-0.169518,...,7.224340,13.670744,19.787706,30.837992,4.061687,8.454161,13.626249,24.564934,34.402798,51.055607
29574,39628004049028142,155.788520,9.066841,0.106881,0.000015,155.788526,9.066844,EXP,3.219153,-0.676203,...,2.810007,5.117693,7.334317,12.570002,2.500480,4.990079,7.716081,13.088153,17.841019,28.065685

In [18]:
df1[["ra_1", "dec_2"]].describe()

               ra_1         dec_2
count  29575.000000  29575.000000
mean     149.983205      1.190027
std        5.151742      4.163131
min      140.122821     -7.766210
25%      145.814499     -1.830818
50%      149.731797      1.422494
75%      154.510996      3.646157
max      159.998141     12.119442

In [19]:
df2[["ra", "dec"]].describe()

                 ra           dec
count  29575.000000  29575.000000
mean     149.983205      1.190027
std        5.151742      4.163131
min      140.122821     -7.766210
25%      145.814499     -1.830818
50%      149.731797      1.422494
75%      154.510996      3.646157
max      159.998141     12.119442

In [21]:
df2.to_csv("../../data/features_images_20260707.csv", sep=",", index=False)