### En este script, buscaré hacer crossmatch del dataframe que contiene features de los stamps
con otro dataframe que contiene las columnas de los flujos para aperturas de distinto radio (Obtenidos del tractor catalog)

- los radios de apertura que se consideran son hasta un radio de 3.5 [arcsec], esto es porque s eprobarán en el nivel con mejor resolución.
- solo se agregan los flujos de apertura considerando las bandas griz.

![imagen de apertura de flujos](../../figures/aperture_fluxes.jpg)

In [1]:
## Importación de librerías

import numpy as np
import pandas as pd

In [2]:
df1 = pd.read_csv("../../data/crossmatch_apflux.txt", sep=",")
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 29575 entries, 0 to 29574
Data columns (total 83 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ra_1                29575 non-null  float64
 1   dec_1               29575 non-null  float64
 2   type_1              29575 non-null  str
 3   shape_r_1           29575 non-null  float64
 4   shape_e1_1          29575 non-null  float64
 5   shape_e2_1          29575 non-null  float64
 6   sersic_1            29575 non-null  float64
 7   ebv_1               29575 non-null  float64
 8   maskbits_1          29575 non-null  int64
 9   apflux_g_0_5        29575 non-null  float64
 10  apflux_g_0_75       29575 non-null  float64
 11  apflux_g_1_0        29575 non-null  float64
 12  apflux_g_1_5        29575 non-null  float64
 13  apflux_g_2_0        29575 non-null  float64
 14  apflux_g_3_5        29575 non-null  float64
 15  apflux_r_0_5        29575 non-null  float64
 16  apflux_r_0_75       29575 non-null  float64
 17  apflux_r_1_0        29575 non-null  float64
 18  apflux_r_1_5        29575 non-null  float64
 19  apflux_r_2_0        29575 non-null  float64
 20  apflux_r_3_5        29575 non-null  float64
 21  apflux_i_0_5        29575 non-null  float64
 22  apflux_i_0_75       29575 non-null  float64
 23  apflux_i_1_0        29575 non-null  float64
 24  apflux_i_1_5        29575 non-null  float64
 25  apflux_i_2_0        29575 non-null  float64
 26  apflux_i_3_5        29575 non-null  float64
 27  apflux_z_0_5        29575 non-null  float64
 28  apflux_z_0_75       29575 non-null  float64
 29  apflux_z_1_0        29575 non-null  float64
 30  apflux_z_1_5        29575 non-null  float64
 31  apflux_z_2_0        29575 non-null  float64
 32  apflux_z_3_5        29575 non-null  float64
 33  id_1                29575 non-null  str
 34  desi_id             29575 non-null  int64
 35  mean_fiber_ra       29575 non-null  float64
 36  mean_fiber_dec      29575 non-null  float64
 37  z                   29575 non-null  float64
 38  zerr                29575 non-null  float64
 39  ra_2                29575 non-null  float64
 40  dec_2               29575 non-null  float64
 41  type_2              29575 non-null  str
 42  shape_r_2           29575 non-null  float64
 43  shape_e1_2          29575 non-null  float64
 44  shape_e2_2          29575 non-null  float64
 45  sersic_2            29575 non-null  float64
 46  ebv_2               29575 non-null  float64
 47  brickid             29575 non-null  int64
 48  dchisq_psf          29575 non-null  float64
 49  dchisq_rex          29575 non-null  float64
 50  dchisq_exp          29575 non-null  float64
 51  dchisq_dev          29575 non-null  float64
 52  dchisq_ser          29575 non-null  float64
 53  id_2                29575 non-null  str
 54  flux_g              29575 non-null  float64
 55  flux_r              29575 non-null  float64
 56  flux_i              29575 non-null  float64
 57  flux_z              29575 non-null  float64
 58  flux_w1             29575 non-null  float64
 59  flux_w2             29575 non-null  float64
 60  flux_w3             29575 non-null  float64
 61  flux_w4             29575 non-null  float64
 62  flux_ivar_g         29575 non-null  float64
 63  flux_ivar_r         29575 non-null  float64
 64  flux_ivar_i         29575 non-null  float64
 65  flux_ivar_z         29575 non-null  float64
 66  flux_ivar_w1        29575 non-null  float64
 67  flux_ivar_w2        29575 non-null  float64
 68  flux_ivar_w3        29575 non-null  float64
 69  flux_ivar_w4        29575 non-null  float64
 70  mw_transmission_i   29575 non-null  float64
 71  fitbits             29575 non-null  int64
 72  mw_transmission_w1  29575 non-null  float64
 73  brickname           29575 non-null  str
 74  mw_transmission_z   29575 non-null  float64
 75  mw_transmission_g   29575 non-null  float64
 76  maskbits_2          29575 non-null  int64
 77  mw_transmission_w2  29575 non-null  float64
 78  mw_transmission_w3  29575 non-null  float64
 79  objid               29575 non-null  int64
 80  mw_transmission_w4  29575 non-null  float64
 81  mw_transmission_r   29575 non-null  float64
 82  Separation          29575 non-null  float64
dtypes: float64(72), int64(6), str(5)
memory usage: 21.0 MB

In [3]:
df1.columns.tolist()

['ra_1',
 'dec_1',
 'type_1',
 'shape_r_1',
 'shape_e1_1',
 'shape_e2_1',
 'sersic_1',
 'ebv_1',
 'maskbits_1',
 'apflux_g_0_5',
 'apflux_g_0_75',
 'apflux_g_1_0',
 'apflux_g_1_5',
 'apflux_g_2_0',
 'apflux_g_3_5',
 'apflux_r_0_5',
 'apflux_r_0_75',
 'apflux_r_1_0',
 'apflux_r_1_5',
 'apflux_r_2_0',
 'apflux_r_3_5',
 'apflux_i_0_5',
 'apflux_i_0_75',
 'apflux_i_1_0',
 'apflux_i_1_5',
 'apflux_i_2_0',
 'apflux_i_3_5',
 'apflux_z_0_5',
 'apflux_z_0_75',
 'apflux_z_1_0',
 'apflux_z_1_5',
 'apflux_z_2_0',
 'apflux_z_3_5',
 'id_1',
 'desi_id',
 'mean_fiber_ra',
 'mean_fiber_dec',
 'z',
 'zerr',
 'ra_2',
 'dec_2',
 'type_2',
 'shape_r_2',
 'shape_e1_2',
 'shape_e2_2',
 'sersic_2',
 'ebv_2',
 'brickid',
 'dchisq_psf',
 'dchisq_rex',
 'dchisq_exp',
 'dchisq_dev',
 'dchisq_ser',
 'id_2',
 'flux_g',
 'flux_r',
 'flux_i',
 'flux_z',
 'flux_w1',
 'flux_w2',
 'flux_w3',
 'flux_w4',
 'flux_ivar_g',
 'flux_ivar_r',
 'flux_ivar_i',
 'flux_ivar_z',
 'flux_ivar_w1',
 'flux_ivar_w2',
 'flux_ivar_w3',
 'flux_ivar_w4',
 'mw_transmission_i',
 'fitbits',
 'mw_transmission_w1',
 'brickname',
 'mw_transmission_z',
 'mw_transmission_g',
 'maskbits_2',
 'mw_transmission_w2',
 'mw_transmission_w3',
 'objid',
 'mw_transmission_w4',
 'mw_transmission_r',
 'Separation']

In [4]:
df2 = pd.read_csv("../../data/features_images_20260618.csv", sep=",")
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 29575 entries, 0 to 29574
Data columns (total 48 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   desi_id             29575 non-null  int64
 1   mean_fiber_ra       29575 non-null  float64
 2   mean_fiber_dec      29575 non-null  float64
 3   z                   29575 non-null  float64
 4   zerr                29575 non-null  float64
 5   ra                  29575 non-null  float64
 6   dec                 29575 non-null  float64
 7   type                29575 non-null  str
 8   shape_r             29575 non-null  float64
 9   shape_e1            29575 non-null  float64
 10  shape_e2            29575 non-null  float64
 11  sersic              29575 non-null  float64
 12  ebv                 29575 non-null  float64
 13  brickid             29575 non-null  int64
 14  dchisq_psf          29575 non-null  float64
 15  dchisq_rex          29575 non-null  float64
 16  dchisq_exp          29575 non-null  float64
 17  dchisq_dev          29575 non-null  float64
 18  dchisq_ser          29575 non-null  float64
 19  id                  29575 non-null  str
 20  flux_g              29575 non-null  float64
 21  flux_r              29575 non-null  float64
 22  flux_i              29575 non-null  float64
 23  flux_z              29575 non-null  float64
 24  flux_w1             29575 non-null  float64
 25  flux_w2             29575 non-null  float64
 26  flux_w3             29575 non-null  float64
 27  flux_w4             29575 non-null  float64
 28  flux_ivar_g         29575 non-null  float64
 29  flux_ivar_r         29575 non-null  float64
 30  flux_ivar_i         29575 non-null  float64
 31  flux_ivar_z         29575 non-null  float64
 32  flux_ivar_w1        29575 non-null  float64
 33  flux_ivar_w2        29575 non-null  float64
 34  flux_ivar_w3        29575 non-null  float64
 35  flux_ivar_w4        29575 non-null  float64
 36  mw_transmission_i   29575 non-null  float64
 37  fitbits             29575 non-null  int64
 38  mw_transmission_w1  29575 non-null  float64
 39  brickname           29575 non-null  str
 40  mw_transmission_z   29575 non-null  float64
 41  mw_transmission_g   29575 non-null  float64
 42  maskbits            29575 non-null  int64
 43  mw_transmission_w2  29575 non-null  float64
 44  mw_transmission_w3  29575 non-null  float64
 45  objid               29575 non-null  int64
 46  mw_transmission_w4  29575 non-null  float64
 47  mw_transmission_r   29575 non-null  float64
dtypes: float64(40), int64(5), str(3)
memory usage: 12.4 MB

In [5]:
df1.rename(columns={"id_1": "id"}, inplace=True)

In [6]:
cols = [
 'apflux_g_0_5',
 'apflux_g_0_75',
 'apflux_g_1_0',
 'apflux_g_1_5',
 'apflux_g_2_0',
 'apflux_g_3_5',
 'apflux_r_0_5',
 'apflux_r_0_75',
 'apflux_r_1_0',
 'apflux_r_1_5',
 'apflux_r_2_0',
 'apflux_r_3_5',
 'apflux_i_0_5',
 'apflux_i_0_75',
 'apflux_i_1_0',
 'apflux_i_1_5',
 'apflux_i_2_0',
 'apflux_i_3_5',
 'apflux_z_0_5',
 'apflux_z_0_75',
 'apflux_z_1_0',
 'apflux_z_1_5',
 'apflux_z_2_0',
 'apflux_z_3_5'
]

df2 = df2.merge(df1[["id"] + cols], on="id", how="left")

In [7]:
df2

,desi_id,mean_fiber_ra,mean_fiber_dec,z,zerr,ra,dec,type,shape_r,shape_e1,...,apflux_i_1_0,apflux_i_1_5,apflux_i_2_0,apflux_i_3_5,apflux_z_0_5,apflux_z_0_75,apflux_z_1_0,apflux_z_1_5,apflux_z_2_0,apflux_z_3_5
0,39627636401508885,147.028920,-6.291707,0.863852,0.000078,147.028933,-6.291716,REX,1.202857,0.000000,...,1.618287,2.824085,3.970746,5.953901,1.226489,2.285031,3.282732,5.122114,6.303779,8.538887
1,39627654457984508,147.941447,-5.506874,1.160004,0.000053,147.941456,-5.506887,EXP,0.358474,-0.312599,...,0.657919,1.653962,3.094118,5.380985,0.298019,0.567938,0.875079,2.170063,4.450177,7.377753
2,39627720786707922,148.820687,-2.767029,0.333578,0.000005,148.820681,-2.767036,REX,0.305442,0.000000,...,0.539180,0.753042,0.889007,0.928609,0.432809,0.771827,1.040121,1.274243,1.581825,1.578013
3,39627660615225397,156.331311,-5.158549,0.159566,0.000016,156.331327,-5.158570,SER,0.509001,-0.049165,...,16.780027,21.812925,24.622234,27.709324,8.634648,14.768244,19.715448,25.946070,29.440456,33.968082
4,39627678684283452,156.207028,-4.541228,0.864645,0.000132,156.207011,-4.541233,REX,0.279362,0.000000,...,1.379479,1.734317,2.011908,2.467141,1.041979,1.832427,2.407057,2.917904,3.242423,3.496601
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29570,39627968078679914,151.770335,7.574563,0.125753,0.000014,151.770339,7.574556,EXP,0.748664,0.079242,...,0.592710,1.061646,1.358798,1.387099,0.352579,0.662510,0.940296,1.238258,1.519247,2.346157
29571,39627805423568301,153.560091,0.738629,0.981242,0.000049,153.560079,0.738607,REX,0.830543,0.000000,...,0.658777,0.986309,1.256300,1.825242,0.314888,0.639176,0.939050,1.371851,1.586630,2.396377
29572,39627841737851674,158.033419,2.225420,0.905659,0.000019,158.033423,2.225414,REX,0.405263,0.000000,...,0.906128,1.167059,1.371384,1.776204,0.398495,0.749987,0.985777,1.414899,1.539899,1.715157
29573,39627889993320651,156.590201,4.210283,0.073323,0.000003,156.590189,4.210277,SER,1.827961,-0.169518,...,15.121942,27.631538,39.055183,60.613800,5.872942,12.130471,19.496810,34.503933,47.785866,70.847855
29574,39628004049028142,155.788520,9.066841,0.106881,0.000015,155.788526,9.066844,EXP,3.219153,-0.676203,...,11.340096,19.407310,26.537449,41.311012,5.584312,10.838488,16.547396,27.198341,36.329205,54.987280

In [9]:
df1[["ra_1", "dec_1"]].describe()

               ra_1         dec_1
count  29575.000000  29575.000000
mean     149.983205      1.190027
std        5.151742      4.163131
min      140.122821     -7.766210
25%      145.814499     -1.830818
50%      149.731797      1.422494
75%      154.510996      3.646157
max      159.998141     12.119442

In [10]:
df2[["ra", "dec"]].describe()

                 ra           dec
count  29575.000000  29575.000000
mean     149.983205      1.190027
std        5.151742      4.163131
min      140.122821     -7.766210
25%      145.814499     -1.830818
50%      149.731797      1.422494
75%      154.510996      3.646157
max      159.998141     12.119442

In [11]:
df2.to_csv("../../data/features_images_20260707.csv", sep=",", index=False)